# HTTP Server
[server]
	Address     = ":5555"
	ServerRoot  = "public"
	ServerAgent = "gf-ipReq"
	LogPath     = "/tmp/log/gf-app/server"

# Logger.
[logger]
    Path        = "/tmp/log/gf-app"
    Level       = "all"
    Stdout      = true

# Template.
[viewer]
    Path        = "template"
    DefaultFile = "index.html"
    Delimiters  =  ["{{", "}}"]

[database]
    link = "sqlite:sqlite/ipreq.db"